// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ContactController from "./contact_controller"
application.register("contact", ContactController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IndexController from "./index_controller"
application.register("index", IndexController)

import RichtextController from "./richtext_controller"
application.register("richtext", RichtextController)
